components:
  parameters: null
  schemas:
    Product:
      type: object
      required:
        - _id
        - name
      properties:
        _id:
          type: number
          description: id
        name:
          type: string
          description: 제품 이름
